insightvista/
  README.md
  .gitignore
  backend/
    .env
    package.json
    jest.config.js
    src/
      server.js
      app.js
      config/
        db.js
      middleware/
        authMiddleware.js
      models/
        User.js
        Dataset.js
      routes/
        auth.js
        data.js
        insights.js
      tests/
        auth.test.js
        data.test.js
  frontend/
    .env
    package.json
    postcss.config.js
    tailwind.config.js
    src/
      index.js
      App.js
      services/
        api.js
      context/
        AuthContext.js
      components/
        Navbar.js
        Sidebar.js
        ProtectedRoute.js
      pages/
        LoginPage.js
        RegisterPage.js
        Dashboard.js
        UploadPage.js
        InsightsPage.js
        NotFoundPage.js
      __tests__/
        App.test.js
